services:
  # 构建 PostgreSQL Operator
  postgres-operator-builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    image: postgres-operator:builder
    volumes:
      - ./bin:/output
    command: >
      sh -c "
        echo '=== 复制构建结果 ===' &&
        cp /app/bin/postgres-operator /output/ 2>/dev/null || echo '构建文件已在镜像中' &&
        echo '=== 构建任务完成 ==='
      "

  # 运行时镜像构建
  postgres-operator:
    build:
      context: .
      dockerfile: build/postgres-operator/Dockerfile
    image: postgres-operator:latest
    depends_on:
      - postgres-operator-builder
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8091:8091"
    environment:
      - PGO_NAMESPACE=postgres-operator
      - CRUNCHY_DEBUG=true
      - PGO_FEATURE_GATES=AllAlpha=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  # 可选：PostgreSQL 测试数据库
  postgres-test:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # 可选：pgAdmin 管理界面
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  default:
    name: postgres-operator-network
